server:
  port: ${PORT:8080}

spring:
  main:
    lazy-initialization: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariPoolContied
      max-lifetime: 1800000
      connection-timeout: 300000
      data-source-properties:
        prepareThreshold: 0
  
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true

supabase:
  jwt:
    public_key: "${SUPABASE_JWT_PUBLIC_KEY}"

ai:
  server:
    url: ${AI_SERVER_URL:http://localhost:8000}
